### ISSUE TITLE
(browser) implement TAB for identation

### ISSUE THREAD

**Issue by TBD** [evanw/sky#1]
**problem**
using TAB in browser implementation will jump to next HTML element (in our case, the close button in browser tab)

**solutions**
1. override browser shortcut 
_cons:_ accessibility problem
2. use a different shortcut (eg CMD+])
3. automatic code formatting
_cons:_ hard to get it right
4. ???

**Comment by TBD** [comment]
looks like 908d820293658fe045f3491d9bd06e43d0d201d0 implements solution 1 (override browser shortcut)

**Comment by evanw** [comment]
Haha I'm definitely not done yet. The way it is right now (1 tab stop == 1 space) is awful. Tab stops are variable-width characters so I thought I'd take the time to implement general support for those along the way. That work hasn't been done yet. I wasn't sure how to respond to this because I ultimately plan to do all three (more shortcuts and auto-indent). I also plan to overload the tab key to trigger word completion when that is implemented, which would be a fourth thing I guess.
